global
        ulimit-n  51200

defaults
        log global
        mode    tcp
        option  dontlognull
        timeout connect 1000
        timeout client 150000
        timeout server 150000

frontend ss-in
        bind *:3108
        default_backend ss-out

backend ss-out
        server server1 xx.xx.xx.xx:3108 maxconn 20480
